
website_build:	## build website
	@npm --prefix website run build

admin_build:	## build website
	@npm --prefix admin run build


help:           ## How to use this makefile
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/:\(.*\)##\(.*\)/:\2/'

